import java.util.ArrayList;
import java.util.List;


public class TriangleNumbers {

    /*
    The sequence of triangle numbers is generated by adding the natural numbers.
    So the7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.   These are the summations
    The first ten terms would be:

    1, 3, 6, 10, 15, 21, 28,36, 45, 55, ...
    Let us list the factors of the first seven triangle numbers:
    1: 1                         1
    3: 1,3                       1+2
    6: 1,2,3,6                   1+2+3
    10: 1,2,5,10                 1+2+3+4
    15: 1,3,5,15                 1+2+3+4+5
    21: 1,3,7,21                 1+2+3+4+5+6
    28: 1,2,4,7,14,28            1+2+3+4+5+6+7
    36: 1,2,3,4,6,9,12,18,36     1+2+3+4+5+6+7+8
    45: 1,3,5,9,15,45            1+2+3+4+5+6+7+8+9
    55: 1,5,11,55        55 is the term, 1, 5, 11, 55 are the divisors

naturalnumber upper# arraysize array
@15 120 [1, 2, 3, 4, 5, 6, 8, 10, 12, 15, 20, 24, 30, 40, 60, 120]

    We can see that 28 is the first triangle number to have over five divisors.
    What is the value of the first triangle number to have over five hundred divisors?

    Answer:

    Divisor: 501
    Value of the first triangle number:103672800
    Triangle number.12375


     */

    public static void findTriangleNumber(int naturalNumber){

        boolean isTriNumber = false;

        List<Integer> triangleArray = new ArrayList<>();        // empty arrayList resizeable

        ArrayList<Integer> termsArray = new ArrayList<>();



        int sum = 0;
        for(int x=1; x<=naturalNumber; x++){
            sum = sum + x;
            termsArray.add(sum);
        }

        int remainder = 0;
        int divisor = 0;
        int term = 0;
        int answer=0;
        int whatIsIndexofValue = 0;
        int count = 0;
        for(Integer e: termsArray){       // e has all the terms by the termsArray

            count = count + 1;
            triangleArray.clear();

            for(int i = 1; i<=e; i++) {

                remainder = e % i;

                if (remainder == 0) {

                    triangleArray.add(i);

                }

                if(divisor<triangleArray.size()){
                    divisor = triangleArray.size();
                    term = e;

                    if(divisor>500 && isTriNumber == false){
                        isTriNumber = true;
                        answer = divisor;
                        term = e;
                        whatIsIndexofValue = count;

                    }

                }
            }

        }

        System.out.print("Divisor: "+answer+" ");
        System.out.print("\n");
        System.out.print("Value of the first triangle number: "+term);
        System.out.print("\n");
        System.out.print("Triangle number: "+whatIsIndexofValue);


    }

    public static void main(String[] args) {

           int num = 15000;
           findTriangleNumber(num);

      }

}
